# Generated by Django 2.1.1 on 2019-03-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
    ]
